const forbiddenWordsChecker = new Set([
  'sex',
  'beastialism',
  'beastiality',
  'bestiality',
  'Horse',
  'tenicles',
  'tentacle',
  'tentacles',
  'tenticles',
  'zoophilia',
  'zoofilia',
  'illegal',
  'necrophilia',
  'counterfeit',
  'coke',
  'drugs',
  'molly',
  'pharm',
  'molested',
  'molester',
  'molesting',
  'molests',
  'murder',
  'murdered',
  'murderer',
  'murdering',
  'murders',
  'pass out',
  'passed out',
  'passing out',
  'pistol',
  'r***',
  'r**e',
  'r*pe',
  'ra**',
  'ra*e',
  'pharmacy',
  'prescription',
  'mutilate',
  'mutilated',
  'mutilates',
  'mutilating',
  'mutilation',
  'mutilator',
  'fecal',
  'faeces',
  'feces',
  'menstrual',
  'menstruate',
  'menstruation',
  'poo',
  'scat',
  'shit',
  '***e',
  '**pe',
  '*ape',
  'abducted',
  'abduction',
  'abuse',
  'abused',
  'abuses',
  'abusing',
  'alcohol',
  'alcohool',
  'asleep',
  'attack',
  'beer',
  'booze',
  'champagne',
  'cocktail',
  'berserk',
  'bled',
  'bleed',
  'bleeding',
  'bleeds',
  'blood',
  'Bloody',
  'Blud',
  'brutal',
  'brutalisation',
  'brutality',
  'sleep',
  'sleeping',
  'sleeps',
  'slept',
  'smother',
  'smothered',
  'smothering',
  'snuff',
  'snuffed',
  'snuffing',
  'snuffs',
  'strangle',
  'suffocate',
  'suffocating',
  'suffocation',
  'sword',
  'torture',
  'tortured',
  'tortures',
  'torturing',
  'tequila',
  'unconscious',
  'unconsciousness',
  'brutalization',
  'brutalise',
  'brutalize',
  'brutalized',
  'brutalizes',
  'brutalizing',
  'brutally',
  'cannibalism',
  'chloro',
  'chloroform',
  'chloroformed',
  'chloroformic',
  'chloroforming',
  'chloroformism',
  'chloroforms',
  'Choke',
  'Choked',
  'chokes',
  'choking',
  'coerce',
  'coerced',
  'drugged',
  'drugging',
  'cocaine',
  'marijuana',
  'Popper',
  'poppers',
  'drunk',
  'drunken',
  'drunkenly',
  'drunkenness',
  'force',
  'forceable',
  'forced',
  'forced',
  'forceful',
  'forcefully',
  'forcer',
  'forces',
  'forcible',
  'forcing',
  'forcingly',
  'gun',
  'hypno',
  'hypnodomme',
  'hypnose',
  'hypnosis',
  'hypnotised',
  'hypnotism',
  'hypnotise',
  'hypnotize',
  'hypnotized',
  'hypnotizes',
  'hypnotizing',
  'incapacitate',
  'incapacitated',
  'incapacitates',
  'incapacitating',
  'incapacitation',
  'inebriate',
  'inebriated',
  'intoxicant',
  'intoxicate',
  'intoxicated',
  'intoxicates',
  'intoxicating',
  'intoxication',
  'involuntarily',
  'involuntary',
  'inzest',
  'kidnap',
  'kidnaped',
  'kidnaper',
  'kidnapper',
  'kidnaping',
  'kidnapped',
  'kidnapping',
  'kill',
  'Killed',
  'Killing',
  'kills',
  'knife',
  'liqor',
  'liquor',
  'molest',
  'molestation',
  'pukes',
  'puking',
  'tipsy',
  'vomit',
  'unwilling',
  'unwillingly',
  'unwillingness',
  'violate',
  'violated',
  'violates',
  'violating',
  'violation',
  'violence',
  'violent',
  'vodka',
  'wasted',
  'whisky',
  'whiskey',
  'wine',
  'gamble',
  'gambling',
  '6teen',
  '7teen',
  'child',
  'child like',
  'childhood',
  'childlike',
  'children',
  'infancy',
  'infant',
  'infant like',
  'infanthood',
  'infantlike',
  'infants',
  'kid',
  'lolita',
  'lolicon',
  'minor',
  'paedophile',
  'paedophilia',
  'paedophiliac',
  'pedo',
  'pedofile',
  'pedophile',
  'pedophilia',
  'pedophiliac',
  'peta',
  'alien',
  'animal',
  'animals',
  'barn',
  'beast',
  'beastliness',
  'farm',
  'monster',
  'zoo',
  'horse',
  'family',
  'coprophilia',
  'coprophiliac',
  'coprophilic',
  'coprophilism',
  'coprophilous',
  'asphyxia',
  'asphyxiate',
  'asphyxiated',
  'asphyxiates',
  'asphyxiating',
  'asphyxiation',
  'dream',
  'drink',
  'drinking',
  'drug',
  'gagged',
  'hate',
  'loaded',
  'nap',
  'puke',
  'puked',
  'pukes',
  'puking',
  'tipsy',
  'vomit',
  'vomited',
  'vomiting',
  'vomits',
  'wake',
  'brother',
  'dad',
  'daddies',
  'daddy',
  'daughter',
  'escort',
  'father',
  'golden showers',
  'incest',
  'incestuous',
  'incestus',
  'law enforcement',
  'mama',
  'mammi',
  'mammy',
  'mom',
  'mother',
  'necromania',
  'necrophile',
  'necrophiliac',
  'necrophilic',
  'necrophilism',
  'pee',
  'piss',
  'pissing',
  'sister',
  'son',
  'urine',
  'watersports',
]);

exports.forbiddenWordsMiddleware = function (propertyName) {
  return function (req, res, next) {
    function checkForbiddenWords(input, property) {
      if (property === 'text') {
        property = 'postText';
      }
      const words = input.split(/\s+/);
      for (const word of words) {
        if (forbiddenWordsChecker.has(word.toLowerCase())) {
          return {
            success: false,
            code: 400,
            errors: {
              [property]: `Forbidden word detected`,
            },
          };
        }
      }
      return null;
    }

    if (Array.isArray(propertyName)) {
      for (const property of propertyName) {
        const input = req.body[property] || '';
        const errorResponse = checkForbiddenWords(input, property);
        if (errorResponse) {
          return res.status(400).json(errorResponse);
        }
      }
    } else {
      const input = req.body[propertyName] || '';
      const errorResponse = checkForbiddenWords(input, propertyName);
      if (errorResponse) {
        return res.status(400).json(errorResponse);
      }
    }

    next();
  };
};
