const forbiddenWordsChecker = new Set([
  'sex',
  'beastialism',
  'beastiality',
  'bestiality',
  'Horse',
  'tenicles',
  'tentacle',
  'tentacles',
  'tenticles',
  'zoophilia',
  'zoofilia',
  'illegal',
  'necrophilia',
  'counterfeit',
  'coke',
  'drugs',
  'molly',
  'pharm',
  'molested',
  'molester',
  'molesting',
  'molests',
  'murder',
  'murdered',
  'murderer',
  'murdering',
  'murders',
  'pass out',
  'passed out',
  'passing out',
  'pistol',
  'r***',
  'r**e',
  'r*pe',
  'ra**',
  'ra*e',
  'pharmacy',
  'prescription',
  'mutilate',
  'mutilated',
  'mutilates',
  'mutilating',
  'mutilation',
  'mutilator',
  'fecal',
  'faeces',
  'feces',
  'menstrual',
  'menstruate',
  'menstruation',
  'poo',
  'scat',
  'shit',
  '***e',
  '**pe',
  '*ape',
  'abducted',
  'abduction',
  'abuse',
  'abused',
  'abuses',
  'abusing',
  'alcohol',
  'alcohool',
  'asleep',
  'attack',
  'beer',
  'booze',
  'champagne',
  'cocktail',
  'berserk',
  'bled',
  'bleed',
  'bleeding',
  'bleeds',
  'blood',
  'Bloody',
  'Blud',
  'brutal',
  'brutalisation',
  'brutality',
  'sleep',
  'sleeping',
  'sleeps',
  'slept',
  'smother',
  'smothered',
  'smothering',
  'snuff',
  'snuffed',
  'snuffing',
  'snuffs',
  'strangle',
  'suffocate',
  'suffocating',
  'suffocation',
  'sword',
  'torture',
  'tortured',
  'tortures',
  'torturing',
  'tequila',
  'unconscious',
  'unconsciousness',
  'brutalization',
  'brutalise',
  'brutalize',
  'brutalized',
  'brutalizes',
  'brutalizing',
  'brutally',
  'cannibalism',
  'chloro',
  'chloroform',
  'chloroformed',
  'chloroformic',
  'chloroforming',
  'chloroformism',
  'chloroforms',
  'Choke',
  'Choked',
  'chokes',
  'choking',
  'coerce',
  'coerced',
  'drugged',
  'drugging',
  'cocaine',
  'marijuana',
  'Popper',
  'poppers',
  'drunk',
  'drunken',
  'drunkenly',
  'drunkenness',
  'force',
  'forceable',
  'forced',
  'forced',
  'forceful',
  'forcefully',
  'forcer',
  'forces',
  'forcible',
  'forcing',
  'forcingly',
  'gun',
  'hypno',
  'hypnodomme',
  'hypnose',
  'hypnosis',
  'hypnotised',
  'hypnotism',
  'hypnotise',
  'hypnotize',
  'hypnotized',
  'hypnotizes',
  'hypnotizing',
  'incapacitate',
  'incapacitated',
  'incapacitates',
  'incapacitating',
  'incapacitation',
  'inebriate',
  'inebriated',
  'intoxicant',
  'intoxicate',
  'intoxicated',
  'intoxicates',
  'intoxicating',
  'intoxication',
  'involuntarily',
  'involuntary',
  'inzest',
  'kidnap',
  'kidnaped',
  'kidnaper',
  'kidnapper',
  'kidnaping',
  'kidnapped',
  'kidnapping',
  'kill',
  'Killed',
  'Killing',
  'kills',
  'knife',
  'liqor',
  'liquor',
  'molest',
  'molestation',
  'pukes',
  'puking',
  'tipsy',
  'vomit',
  'unwilling',
  'unwillingly',
  'unwillingness',
  'violate',
  'violated',
  'violates',
  'violating',
  'violation',
  'violence',
  'violent',
  'vodka',
  'wasted',
  'whisky',
  'whiskey',
  'wine',
  'gamble',
  'gambling',
  '6teen',
  '7teen',
  'child',
  'child like',
  'childhood',
  'childlike',
  'children',
  'infancy',
  'infant',
  'infant like',
  'infanthood',
  'infantlike',
  'infants',
  'kid',
  'lolita',
  'lolicon',
  'minor',
  'paedophile',
  'paedophilia',
  'paedophiliac',
  'pedo',
  'pedofile',
  'pedophile',
  'pedophilia',
  'pedophiliac',
  'peta',
  'alien',
  'animal',
  'animals',
  'barn',
  'beast',
  'beastliness',
  'farm',
  'monster',
  'zoo',
  'horse',
  'family',
  'coprophilia',
  'coprophiliac',
  'coprophilic',
  'coprophilism',
  'coprophilous',
  'asphyxia',
  'asphyxiate',
  'asphyxiated',
  'asphyxiates',
  'asphyxiating',
  'asphyxiation',
  'dream',
  'drink',
  'drinking',
  'drug',
  'gagged',
  'hate',
  'loaded',
  'nap',
  'puke',
  'puked',
  'pukes',
  'puking',
  'tipsy',
  'vomit',
  'vomited',
  'vomiting',
  'vomits',
  'wake',
  'brother',
  'dad',
  'daddies',
  'daddy',
  'daughter',
  'escort',
  'father',
  'golden showers',
  'incest',
  'incestuous',
  'incestus',
  'law enforcement',
  'mama',
  'mammi',
  'mammy',
  'mom',
  'mother',
  'necromania',
  'necrophile',
  'necrophiliac',
  'necrophilic',
  'necrophilism',
  'pee',
  'piss',
  'pissing',
  'sister',
  'son',
  'urine',
  'watersports',
]);

const forbiddenUserNames = new Set([
  'register',
  'forgot-password',
  'reset-password',
  'confirm-email',
  'auth/2fa',
  'auth/success',
  'email-tamp',
  'dashboard',
  'action/trial',
  'settings',
  'settings/profile',
  'settings/account',
  'settings/security',
  'settings/security/password',
  'settings/security/sessions',
  'settings/security/2fa',
  'settings/subscription',
  'settings/notifications',
  'settings/display',
  'settings/fans',
  'settings/messaging',
  'settings/story',
  'settings/code',
  'settings/notifications/push',
  'settings/notifications/site',
  'settings/notifications/email',
  'settings/notifications/toast',
  'settings/notifications/sms',
  'settings/account/username',
  'settings/account/email',
  'settings/account/phone',
  'settings/account/delete',
  'settings/account/x',
  'settings/account/google',
  'notifications',
  'bookmarks',
  'bookmarks',
  'lists',
  'list',
  'my',
  'lists/add',
  'subscriptions',
  'payments',
  'payments/add-card',
  'payments/list',
  'chats',
  'chats/send',
  'chats/chat',
  'chats/chat',
  'my/banking',
  'banking/payout-system',
  'w9',
  'w8',
  'payment-srv/kyc/onboarded',
  'posts/create',
  'posts/update',
  'posts/live',
  'post',
  'statistics',
  'statistics/statements',
  'statistics/statements/earnings',
  'statistics/statements/payout-request',
  'statistics/statements/chargebacks',
  'statistics/statements/referrals',
  'statistics/overview',
  'statistics/overview/earnings',
  'statistics/overview/highlights',
  'statistics/engagement',
  'statistics/engagement/posts',
  'statistics/engagement/messages',
  'statistics/engagement/streaming',
  'statistics/engagement/stories',
  'statistics/reach',
  'statistics/reach/visitors',
  'statistics/reach/promotions',
  'statistics/reach/trialLinks',
  'statistics/reach/trackingLinks',
  'statistics/fans',
  'statistics/fans/subscriptions',
  'terms',
  'privacy',
  'faq',
  'vault',
  'queue',
  'post-labels',
  'release',
  'release-forms',
  'contact',
  'about',
  'omnichannel',
  'kyc-id',
  'defending',
  'brand',
  'cookies',
  'usc2257',
]);

exports.forbiddenWordsMiddleware = function (propertyName) {
  return async function (req, res, next) {
    async function checkForbiddenWords(input, property) {
      const words = input.split(/\s+/);
      if (property === 'text') {
        property = 'postText';
      }

      if (
        propertyName.includes(['username', 'displayName']) ||
        property === 'displayName' ||
        property === 'username'
      ) {
        for (const word of words) {
          if (forbiddenUserNames.has(word.toLowerCase())) {
            return {
              success: false,
              code: 400,
              errors: {
                [property]: `Forbidden word detected`,
              },
            };
          }
        }
      }
      for (const word of words) {
        if (forbiddenWordsChecker.has(word.toLowerCase())) {
          return {
            success: false,
            code: 400,
            errors: {
              [property]: `Forbidden word detected`,
            },
          };
        }
      }
      return null;
    }

    if (Array.isArray(propertyName)) {
      for (const property of propertyName) {
        const input = req.body[property] || '';
        const errorResponse = await checkForbiddenWords(input, property);
        if (errorResponse) {
          return res.status(400).json(errorResponse);
        }
      }
    } else {
      const input = req.body[propertyName] || '';
      const errorResponse = await checkForbiddenWords(input, propertyName);
      if (errorResponse) {
        return res.status(400).json(errorResponse);
      }
    }

    next();
  };
};
